### ISSUE TITLE
not working Lite XL v2.1

### ISSUE THREAD

**Issue by beastehg** [devPnal/lite-plugin-autohotkey#7]
https://i.imgur.com/zsnxobC.png

**Comment by Stefanoko** [comment]
I cannot get it to work, either. 
Inside, the file looks totally different from other language files I inspected. And why is it so much bigger? 230 kb in size, that is 100 times bigger compared to the syntax files for python, ruby, java etc.
Something must be definitely wrong here.

**Comment by devPnal** [comment]
Because there are so many built-in variables and functions in AHK. Futhermore, It can support four diffrent version like [Msgbox, msgbox, MSGBOX, MagBox]. So file size is totally okay.

Btw, I can't check the issue over lite-xl v2.1+ because of my personal issue. I'm very busy nowadays. Apologize for it.

Also, you can make PR for this language pack.

Again, I'm very sorry for it.

**Comment by Stefanoko** [comment]
I understand you are busy.
Thank you for taking the time to explain and filling me in.  I really appreciate it. And also the effort you invested into creating this plugin.
